#!/usr/bin/env bash
# pi-reaudit.sh - Post-freeze audit of @mariozechner/pi-coding-agent
# Run on or after 2026-04-13 when Mario's OSS Weekend freeze ends.
# Outputs a report at scripts/pi-reaudit-report-YYYY-MM-DD.md
#
# This script does NOT modify MyPensieve source. It is a read-only audit.
# Read PI-REAUDIT-CHECKLIST.md before interpreting the report.

set -euo pipefail

REPO_URL="https://github.com/badlogic/pi-mono.git"
LOCAL_CLONE="/tmp/pi-mono"
BASELINE_COMMIT="3b7448d156aab5af1e21fd9ab45d19e4f10865a8"
BASELINE_VERSION="0.66.1"
TODAY="$(date +%Y-%m-%d)"
# Resolve REPORT_DIR to an absolute path BEFORE we cd into the pi-mono clone
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPORT_DIR="$SCRIPT_DIR"
REPORT="${REPORT_DIR}/pi-reaudit-report-${TODAY}.md"

# Files we care about (the Surface Watch List from PI-REAUDIT-CHECKLIST.md)
WATCH_FILES=(
  "packages/coding-agent/src/index.ts"
  "packages/coding-agent/src/core/sdk.ts"
  "packages/coding-agent/src/core/agent-session.ts"
  "packages/coding-agent/src/core/extensions/types.ts"
  "packages/coding-agent/src/core/session-manager.ts"
  "packages/coding-agent/src/core/auth-storage.ts"
  "packages/coding-agent/src/core/skills.ts"
  "packages/coding-agent/src/modes/rpc/rpc-mode.ts"
  "packages/coding-agent/docs/sdk.md"
  "packages/coding-agent/docs/skills.md"
  "packages/coding-agent/docs/extensions.md"
  "packages/coding-agent/docs/rpc.md"
  "AGENTS.md"
)

WATCH_DIRS=(
  "packages/coding-agent/examples/extensions"
  "packages/ai/src/providers"
)

log() { printf "[pi-reaudit] %s\n" "$1" >&2; }
section() { printf "\n## %s\n\n" "$1" >> "$REPORT"; }
write() { printf "%s\n" "$1" >> "$REPORT"; }

# Step 0: confirm freeze status
log "Checking freeze status..."
FREEZE_JSON="$(curl -fsSL https://raw.githubusercontent.com/badlogic/pi-mono/main/.github/oss-weekend.json 2>/dev/null || echo '{}')"
FREEZE_ACTIVE="$(printf "%s" "$FREEZE_JSON" | grep -o '"active":[[:space:]]*true' || true)"

# Step 1: update or clone
if [ -d "$LOCAL_CLONE/.git" ]; then
  log "Updating $LOCAL_CLONE..."
  git -C "$LOCAL_CLONE" fetch --quiet origin
  git -C "$LOCAL_CLONE" checkout --quiet main
  git -C "$LOCAL_CLONE" pull --quiet --ff-only
else
  log "Cloning $REPO_URL into $LOCAL_CLONE..."
  git clone --quiet "$REPO_URL" "$LOCAL_CLONE"
fi

cd "$LOCAL_CLONE"
NEW_HEAD="$(git rev-parse HEAD)"
NEW_HEAD_SHORT="$(git rev-parse --short HEAD)"
NEW_VERSION="$(grep -E '"version"' packages/coding-agent/package.json | head -1 | sed -E 's/.*"version": *"([^"]+)".*/\1/')"

# Step 2: write report header
mkdir -p "$REPORT_DIR"
cat > "$REPORT" <<EOF_HEADER
# Pi Re-Audit Report - ${TODAY}

> Auto-generated by scripts/pi-reaudit.sh
> Read PI-REAUDIT-CHECKLIST.md for how to interpret this.

## Baseline vs current

| Field | Baseline (2026-04-09) | Current (${TODAY}) |
|---|---|---|
| Commit | \`${BASELINE_COMMIT:0:7}\` | \`${NEW_HEAD_SHORT}\` |
| Version | \`${BASELINE_VERSION}\` | \`${NEW_VERSION}\` |

## Freeze status
EOF_HEADER

if [ -n "$FREEZE_ACTIVE" ]; then
  write "**WARNING:** Freeze is still active. Audit results may not include the post-freeze refactor."
  write ""
  write "Raw freeze JSON:"
  write '```json'
  printf "%s\n" "$FREEZE_JSON" >> "$REPORT"
  write '```'
else
  write "Freeze inactive (or status file unreachable). Proceeding with audit."
fi

# Step 3: commit log between baseline and current
section "Commits between baseline and current"
write '```'
git log --oneline "${BASELINE_COMMIT}..HEAD" 2>/dev/null >> "$REPORT" || write "(baseline commit not in history - may need force pull)"
write '```'

# Step 4: per-file diff stats
section "Watch list - per-file diff stats"
write "| File | Lines added | Lines removed | Status |"
write "|---|---|---|---|"
for f in "${WATCH_FILES[@]}"; do
  if [ ! -f "$f" ]; then
    write "| \`${f}\` | - | - | **REMOVED** |"
    continue
  fi
  STATS="$(git diff --numstat "${BASELINE_COMMIT}" -- "$f" 2>/dev/null || true)"
  if [ -z "$STATS" ]; then
    write "| \`${f}\` | 0 | 0 | unchanged |"
  else
    ADDED="$(printf "%s" "$STATS" | awk '{print $1}')"
    REMOVED="$(printf "%s" "$STATS" | awk '{print $2}')"
    write "| \`${f}\` | ${ADDED} | ${REMOVED} | changed |"
  fi
done

# Step 5: new files in watched dirs
section "New files in watched directories"
for d in "${WATCH_DIRS[@]}"; do
  write "### \`${d}\`"
  write '```'
  if [ -d "$d" ]; then
    git diff --name-status --diff-filter=A "${BASELINE_COMMIT}" -- "$d" 2>/dev/null >> "$REPORT" || write "(no diff data - check baseline commit)"
  else
    write "(directory missing)"
  fi
  write '```'
done

# Step 6: removed files in watched dirs
section "Removed files in watched directories"
for d in "${WATCH_DIRS[@]}"; do
  write "### \`${d}\`"
  write '```'
  if [ -d "$d" ]; then
    git diff --name-status --diff-filter=D "${BASELINE_COMMIT}" -- "$d" 2>/dev/null >> "$REPORT" || write "(no diff data)"
  else
    write "(directory missing)"
  fi
  write '```'
done

# Step 7: high-level surface checks
section "High-level surface checks"

# check_required: symbol MUST be present (MISSING = Red bucket signal)
check_required() {
  local symbol="$1"
  local file="$2"
  local label="$3"
  if [ -f "$file" ] && grep -q "$symbol" "$file"; then
    write "- ${label}: PRESENT in \`${file}\` (expected)"
  else
    write "- ${label}: **MISSING** from \`${file}\` - **RED BUCKET SIGNAL**"
  fi
}

# check_refactor: symbol that may APPEAR after the refactor (PRESENT = Orange/refactor landed)
check_refactor() {
  local symbol="$1"
  local file="$2"
  local label="$3"
  if [ -f "$file" ] && grep -q "$symbol" "$file"; then
    write "- ${label}: **PRESENT** in \`${file}\` - refactor signal, review N5/PI-FOUNDATION.md"
  else
    write "- ${label}: not present (pre-refactor state, or refactor did not introduce this)"
  fi
}

check_required "AgentSession" "packages/coding-agent/src/core/agent-session.ts" "\`AgentSession\` class"
check_refactor "AgentSessionRuntime" "packages/coding-agent/src/core/agent-session.ts" "\`AgentSessionRuntime\` (post-refactor)"
check_refactor "createAgentSessionServices" "packages/coding-agent/src/core/agent-session.ts" "\`createAgentSessionServices\` factory (post-refactor)"
check_required "runRpcMode" "packages/coding-agent/src/index.ts" "\`runRpcMode\` exported"
check_required "formatSkillsForPrompt" "packages/coding-agent/src/core/skills.ts" "\`formatSkillsForPrompt\` lazy catalog"
check_required "AuthStorage" "packages/coding-agent/src/core/auth-storage.ts" "\`AuthStorage\` interface"

# Check provider list
section "Providers in pi-ai (current state)"
write '```'
if [ -d "packages/ai/src/providers" ]; then
  ls packages/ai/src/providers/ | grep -E '\.ts$' | sort >> "$REPORT" || true
else
  write "(providers directory missing)"
fi
write '```'

# Check npm version (the published one, not the repo version)
section "npm registry check"
NPM_VERSION="$(curl -fsSL "https://registry.npmjs.org/@mariozechner/pi-coding-agent/latest" 2>/dev/null | grep -o '"version":"[^"]*"' | head -1 | sed -E 's/.*"version":"([^"]+)".*/\1/' || echo "unreachable")"
write "Latest published npm version: \`${NPM_VERSION}\`"
write ""
write "Repo \`packages/coding-agent/package.json\` version: \`${NEW_VERSION}\`"
write ""
if [ "$NPM_VERSION" != "$NEW_VERSION" ] && [ "$NPM_VERSION" != "unreachable" ]; then
  write "**Note:** repo version differs from published. Refactor may not be in npm yet."
fi

# Step 8: classification reminder
section "Next step"
write "1. Read this report top-to-bottom."
write "2. Open PI-REAUDIT-CHECKLIST.md and use the **Outcome buckets** table to classify."
write "3. Take the bucket-specific action listed in the checklist."
write "4. Append a one-paragraph outcome note to PI-FOUNDATION.md under a \"Re-audit history\" section."

log "Done. Report written to $REPORT"
log "Read it, then classify per PI-REAUDIT-CHECKLIST.md outcome buckets."
