import fs from "node:fs";
import path from "node:path";
import url from "node:url";
import { PI_DIRS } from "../config/paths.js";
import { captureError } from "../ops/index.js";

export interface InstallExtensionResult {
	bridgePath: string;
	targetPath: string;
	action: "created" | "updated";
}

export class ExtensionInstallError extends Error {
	constructor(
		message: string,
		public readonly cause?: unknown,
	) {
		super(message);
		this.name = "ExtensionInstallError";
	}
}

/**
 * Install a bridge file at ~/.pi/agent/extensions/mypensieve/index.js that
 * re-exports MyPensieve's compiled Pi extension.
 *
 * Pi's extension loader scans ~/.pi/agent/extensions/ for subdirectories
 * containing an `index.js`, `index.ts`, or `package.json` with a pi manifest.
 * We write a tiny re-export bridge whose absolute path resolves to the actual
 * MyPensieve install location (wherever npm installed us), so Pi can load our
 * extension factory without needing mypensieve on its module resolution path.
 */
export function installMyPensieveExtension(): InstallExtensionResult {
	// This file becomes dist/init/extension-installer.js after build.
	// The compiled extension factory lives at dist/core/extension.js.
	const installerDir = path.dirname(url.fileURLToPath(import.meta.url));
	const targetPath = path.resolve(installerDir, "..", "core", "extension.js");

	if (!fs.existsSync(targetPath)) {
		captureError({
			severity: "critical",
			errorType: "extension_target_missing",
			errorSrc: "init:extension-installer",
			message: `MyPensieve extension factory not found at ${targetPath}`,
			context: { targetPath, installerDir },
		});
		throw new ExtensionInstallError(
			`Cannot locate MyPensieve extension factory at ${targetPath}. ` +
				"Is MyPensieve installed correctly?",
		);
	}

	const bridgeDir = PI_DIRS.mypensieveExtensions;
	const bridgePath = path.join(bridgeDir, "index.js");
	const packageJsonPath = path.join(bridgeDir, "package.json");

	const bridgeContent = [
		"// Auto-generated by `mypensieve init`. Do not edit.",
		"// Re-exports the MyPensieve Pi extension factory from its install location.",
		`export { default } from ${JSON.stringify(targetPath)};`,
		"",
	].join("\n");

	// Sibling package.json pins this directory to ESM so Node / jiti resolve
	// the `.js` bridge as a module regardless of any parent package.json.
	const packageJsonContent = `${JSON.stringify(
		{
			name: "mypensieve-pi-extension",
			private: true,
			type: "module",
		},
		null,
		2,
	)}\n`;

	try {
		fs.mkdirSync(bridgeDir, { recursive: true, mode: 0o755 });
	} catch (err) {
		const e = err instanceof Error ? err : new Error(String(err));
		captureError({
			severity: "critical",
			errorType: "extension_mkdir",
			errorSrc: "init:extension-installer",
			message: e.message,
			stack: e.stack,
			context: { bridgeDir },
		});
		throw new ExtensionInstallError(`Failed to create ${bridgeDir}`, err);
	}

	const existed = fs.existsSync(bridgePath);
	try {
		fs.writeFileSync(bridgePath, bridgeContent, "utf-8");
		fs.writeFileSync(packageJsonPath, packageJsonContent, "utf-8");
	} catch (err) {
		const e = err instanceof Error ? err : new Error(String(err));
		captureError({
			severity: "critical",
			errorType: "extension_write",
			errorSrc: "init:extension-installer",
			message: e.message,
			stack: e.stack,
			context: { bridgePath, packageJsonPath },
		});
		throw new ExtensionInstallError(`Failed to write ${bridgePath}`, err);
	}

	return { bridgePath, targetPath, action: existed ? "updated" : "created" };
}
